name: NodeJS with Webpack and angular project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
 
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker/docker-compose.yml"
        
  
         
