name: NodeJS with Webpack and angular project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  
   
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker/docker-compose.yml"
        
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Necessary to access local action
      - name: Local Action Call
        id: local-action
        uses: ./.github/local-action/
       

      
  job3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Necessary to access local action
      - name: Avatar Action Call
        id: avatar
        uses: ./.github/avatar/
        
   
         
