name: NodeJS with Webpack and angular project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          compose-file: "./docker/docker-compose.yml"
          run: docker-compose up -d 
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .        
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/workflowfrontendt:latest
