name: NodeJS with Webpack and angular project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  call-workflow-plataforma-in-local-repo:
    uses: Hackathon-ChatGPT-NTTDATA/plataformaacademica/cursos/.github/workflows/plataforma.yml
  call-workflow-avatar-in-local-repo:
     uses: Hackathon-ChatGPT-NTTDATA/plataformaacademica/cursos/.github/workflows/plataforma.yml

  build:
    runs-on: ubuntu-latest
    
   
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker/docker-compose.yml"
          down-flags: "--volumes"
          services: |
            frontend-plataforma-academica-avatar
